// A minimal, dependency-free PDF writer. It supports a title, a colored
// accent bar, section headings, and label/value rows — enough to produce a
// clean, professional-looking one-page document (confirmation letters, work
// orders, event briefs, client detail sheets) without pulling in a heavy
// PDF library.

type PdfLine =
  | { type: 'title'; text: string }
  | { type: 'subtitle'; text: string }
  | { type: 'heading'; text: string }
  | { type: 'row'; label: string; value: string }
  | { type: 'text'; text: string }
  | { type: 'spacer' };

export class PdfDocumentBuilder {
  private lines: PdfLine[] = [];

  title(text: string) {
    this.lines.push({ type: 'title', text });
    return this;
  }

  subtitle(text: string) {
    this.lines.push({ type: 'subtitle', text });
    return this;
  }

  heading(text: string) {
    this.lines.push({ type: 'spacer' });
    this.lines.push({ type: 'heading', text });
    return this;
  }

  row(label: string, value: string | null | undefined) {
    this.lines.push({ type: 'row', label, value: value || '—' });
    return this;
  }

  text(text: string | null | undefined) {
    this.lines.push({ type: 'text', text: text || '' });
    return this;
  }

  spacer() {
    this.lines.push({ type: 'spacer' });
    return this;
  }

  build(): Buffer {
    return buildPdfFromLines(this.lines);
  }
}

const escapePdfText = (value: string) =>
  String(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');

const PAGE_HEIGHT = 792;
const MARGIN_TOP = 74;
const MARGIN_LEFT = 56;
const ACCENT_RGB = '0.78 0.21 0.10'; // brand red, approximated for PDF color ops
const MUTED_RGB = '0.42 0.45 0.5';
const DARK_RGB = '0.07 0.09 0.15';

const buildPdfFromLines = (lines: PdfLine[]): Buffer => {
  const ops: string[] = [];
  let y = PAGE_HEIGHT - MARGIN_TOP;

  // Header accent bar
  ops.push(`${ACCENT_RGB} rg 0 ${PAGE_HEIGHT - 18} 612 18 re f`);

  for (const line of lines) {
    if (y < 60) break; // simple one-page safeguard

    switch (line.type) {
      case 'title':
        ops.push(`${DARK_RGB} rg BT /F2 20 Tf ${MARGIN_LEFT} ${y} Td (${escapePdfText(line.text)}) Tj ET`);
        y -= 26;
        break;
      case 'subtitle':
        ops.push(`${MUTED_RGB} rg BT /F1 11 Tf ${MARGIN_LEFT} ${y} Td (${escapePdfText(line.text)}) Tj ET`);
        y -= 22;
        break;
      case 'heading':
        ops.push(`${ACCENT_RGB} rg ${MARGIN_LEFT} ${y - 4} 500 1.2 re f`);
        y -= 6;
        ops.push(`${ACCENT_RGB} rg BT /F2 12 Tf ${MARGIN_LEFT} ${y - 10} Td (${escapePdfText(line.text.toUpperCase())}) Tj ET`);
        y -= 24;
        break;
      case 'row':
        ops.push(`${MUTED_RGB} rg BT /F1 10 Tf ${MARGIN_LEFT} ${y} Td (${escapePdfText(line.label)}) Tj ET`);
        ops.push(`${DARK_RGB} rg BT /F2 10.5 Tf ${MARGIN_LEFT + 170} ${y} Td (${escapePdfText(line.value)}) Tj ET`);
        y -= 18;
        break;
      case 'text':
        ops.push(`${DARK_RGB} rg BT /F1 10 Tf ${MARGIN_LEFT} ${y} Td (${escapePdfText(line.text)}) Tj ET`);
        y -= 16;
        break;
      case 'spacer':
        y -= 10;
        break;
    }
  }

  // Footer
  ops.push(`${MUTED_RGB} rg BT /F1 8 Tf ${MARGIN_LEFT} 40 Td (Generated by EventHub360 \\267 ${escapePdfText(new Date().toLocaleString())}) Tj ET`);

  const contentStream = ops.join('\n') + '\n';

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj\n',
    `4 0 obj\n<< /Length ${Buffer.byteLength(contentStream, 'binary')} >>\nstream\n${contentStream}endstream\nendobj\n`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n',
    '6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, 'binary'));
    pdf += obj;
  }

  const xrefOffset = Buffer.byteLength(pdf, 'binary');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, 'binary');
};
